const GLchar* vertex_shader_source =
"attribute vec4 vertex;\n"
"uniform mat4 matrix;\n"
"varying vec3 pos;\n"
"\n"
"varying vec4 screen;\n"
"varying vec3 dir;\n"
"\n"
"uniform float size;\n"
"varying float _Size;\n"
"\n"
"uniform float frames;\n"
"varying float _Frames;\n"
"\n"
"uniform float frame;\n"
"varying float _Frame;\n"
"\n"
"uniform float steps;\n"
"varying float _Steps;\n"
"\n"
"void main(void)\n"
"{\n"
"    gl_Position = matrix * vertex;\n"
"//    gl_Position = vertex;\n"
"    gl_PointSize = 1.0;\n"
"    pos = vertex.xyz;\n"
"    dir = (vec4(0.0, 0.0, 1.0, 1.0) * -matrix).xyz - vertex.xyz;\n"
"    _Size = (size > 1.0) ? ceil(size) : 1.0;\n"
"    _Frames = ceil(frames);\n"
"    _Frame = ceil(frame) / frames;\n"
"    _Steps = (steps > 1.0) ? ceil(steps) : 1.0;\n"
"}\n";
